name: Stryker Mutation Testing

on:
  pull_request:
    branches:
      - master

jobs:
  stryker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker

    - name: Run Stryker
      working-directory: tests/ServiceableBus.Azure.Tests
      run: dotnet stryker -f stryker-config.json

    - name: Upload Stryker Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: stryker-report
        path: ${{github.workspace}}/tests/**/**/*.html